/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import dao.Conection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utilReports.Report;
import utilReports.ReportManager;


/**
 *
 * @author tais
 */
public class TelaPrincipal extends javax.swing.JFrame {

      private TelaCadastroCliente telaCadastroCliente;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagemLogo = new javax.swing.JLabel();
        MenuTelaPrincipal = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenu();
        abrirTelacadastroCliente = new javax.swing.JMenuItem();
        abrirCadastroFilme = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnRelFilmes = new javax.swing.JMenuItem();
        btnRelClientes = new javax.swing.JMenuItem();
        btnRelAvaliacao = new javax.swing.JMenuItem();
        btnRelDuracao = new javax.swing.JMenuItem();
        sairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 100, 100));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        imagemLogo.setIcon(new javax.swing.ImageIcon("/home/tais/Documentos/cine.jpg")); // NOI18N
        imagemLogo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagemLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 569, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagemLogo)
        );

        MenuTelaPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        MenuTelaPrincipal.setForeground(new java.awt.Color(204, 204, 204));
        MenuTelaPrincipal.setMinimumSize(new java.awt.Dimension(154, 21));
        MenuTelaPrincipal.setPreferredSize(new java.awt.Dimension(12, 50));

        jMenu2.setBackground(new java.awt.Color(102, 102, 102));
        jMenu2.setIcon(new javax.swing.ImageIcon("/home/tais/Imagens/camera.png")); // NOI18N
        MenuTelaPrincipal.add(jMenu2);

        cadastrarCliente.setBackground(new java.awt.Color(102, 102, 102));
        cadastrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        cadastrarCliente.setText("Cadastros");

        abrirTelacadastroCliente.setBackground(new java.awt.Color(255, 255, 255));
        abrirTelacadastroCliente.setForeground(new java.awt.Color(0, 0, 0));
        abrirTelacadastroCliente.setText("Cliente");
        abrirTelacadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelacadastroClienteActionPerformed(evt);
            }
        });
        cadastrarCliente.add(abrirTelacadastroCliente);

        abrirCadastroFilme.setBackground(new java.awt.Color(102, 102, 102));
        abrirCadastroFilme.setForeground(new java.awt.Color(0, 0, 0));
        abrirCadastroFilme.setText("FIlme");
        abrirCadastroFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCadastroFilmeActionPerformed(evt);
            }
        });
        cadastrarCliente.add(abrirCadastroFilme);

        MenuTelaPrincipal.add(cadastrarCliente);

        jMenu1.setText("Relatórios");

        btnRelFilmes.setText("Filmes");
        btnRelFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelFilmesActionPerformed(evt);
            }
        });
        jMenu1.add(btnRelFilmes);

        btnRelClientes.setText("Clientes");
        btnRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelClientesActionPerformed(evt);
            }
        });
        jMenu1.add(btnRelClientes);

        btnRelAvaliacao.setText("Filmes por Avaliações");
        btnRelAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelAvaliacaoActionPerformed(evt);
            }
        });
        jMenu1.add(btnRelAvaliacao);

        btnRelDuracao.setText("Filmes por Duração");
        btnRelDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelDuracaoActionPerformed(evt);
            }
        });
        jMenu1.add(btnRelDuracao);

        MenuTelaPrincipal.add(jMenu1);

        sairMenu.setBackground(new java.awt.Color(102, 102, 102));
        sairMenu.setForeground(new java.awt.Color(0, 0, 0));
        sairMenu.setText("Sair");
        sairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuActionPerformed(evt);
            }
        });
        MenuTelaPrincipal.add(sairMenu);

        setJMenuBar(MenuTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadastroFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCadastroFilmeActionPerformed
        TelaCadastroFilmes tCadastroFilmes = new  TelaCadastroFilmes();
        this.setVisible(false);
        tCadastroFilmes.setVisible(true);
    }//GEN-LAST:event_abrirCadastroFilmeActionPerformed

    private void abrirTelacadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelacadastroClienteActionPerformed
        TelaCadastroCliente telaCadastroCliente = new TelaCadastroCliente();
        this.setVisible(false);
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_abrirTelacadastroClienteActionPerformed

    private void sairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuActionPerformed
        dispose();
    }//GEN-LAST:event_sairMenuActionPerformed

    private void btnRelFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelFilmesActionPerformed
        Report r = new Report() {
            @Override
            public HashMap getParameters() {
                return new HashMap();
            }
             @Override
            public String getPath() {

                return "/reports/RelatorioFilmes.jrxml";
            }
         };
         
        Connection conn = null;
        conn = new Conection().getConnection();
         
        
        ReportManager rm = new ReportManager();
        
        try {
            rm.setDataBaseConnection(conn);
        } catch(Exception ex){
            System.out.println("DEU ERRADO " + ex);
        }
        rm.createReport(r);
    }//GEN-LAST:event_btnRelFilmesActionPerformed

    private void btnRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelClientesActionPerformed
  
        Report r = new Report() {
            @Override
            public HashMap getParameters() {
                return new HashMap();
            }
             @Override
            public String getPath() {

                return "/reports/RelatorioClientes.jrxml";
            }
         };
         
        Connection conn = null;
        conn = new Conection().getConnection();
         
        
        ReportManager rm = new ReportManager();
        
        try {
            rm.setDataBaseConnection(conn);
        } catch(Exception ex){
            System.out.println("DEU ERRADO " + ex);
        }
        rm.createReport(r);        
    }//GEN-LAST:event_btnRelClientesActionPerformed

    private void btnRelAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelAvaliacaoActionPerformed
        TelaRelatorioPorAvaliacao telaRelAva = new TelaRelatorioPorAvaliacao();
        this.setVisible(false);
        telaRelAva.setVisible(true);
    }//GEN-LAST:event_btnRelAvaliacaoActionPerformed

    private void btnRelDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelDuracaoActionPerformed
        TelaRelatorioPorDuracao telaRel = new TelaRelatorioPorDuracao();
        this.setVisible(false);
        telaRel.setVisible(true);
    }//GEN-LAST:event_btnRelDuracaoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuTelaPrincipal;
    private javax.swing.JMenuItem abrirCadastroFilme;
    private javax.swing.JMenuItem abrirTelacadastroCliente;
    private javax.swing.JMenuItem btnRelAvaliacao;
    private javax.swing.JMenuItem btnRelClientes;
    private javax.swing.JMenuItem btnRelDuracao;
    private javax.swing.JMenuItem btnRelFilmes;
    private javax.swing.JMenu cadastrarCliente;
    private javax.swing.JLabel imagemLogo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu sairMenu;
    // End of variables declaration//GEN-END:variables
}
