/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import dao.Conection;
import dao.ExceptionDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.FilmeControle;

/**
 *
 * @author tais
 */
public class TelaAvaliacaoFilme extends javax.swing.JFrame {

     int codFilmeAvaliado;
    
    /**
     * Creates new form TelaAvaliacaoFilme
     */
    
    public TelaAvaliacaoFilme() {
        initComponents();
    }
     
    public TelaAvaliacaoFilme(int codFilme) {
        initComponents();
        this.codFilmeAvaliado = codFilme;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDois = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnQuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnUm = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Avaliação");

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/tais/Documentos/2022A/Aplicações/HeroFlix/src/main/java/imagens/estrelinha-da-tais.png")); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Gostaríamos de saber a sua opinião sobre o Filme!");

        btnDois.setBackground(new java.awt.Color(0, 0, 0));
        btnDois.setIcon(new javax.swing.ImageIcon("/home/tais/Documentos/2022A/Aplicações/HeroFlix/src/main/java/imagens/estrelinha-da-tais.png")); // NOI18N
        btnDois.setBorder(null);
        btnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoisActionPerformed(evt);
            }
        });

        btnTres.setBackground(new java.awt.Color(0, 0, 0));
        btnTres.setIcon(new javax.swing.ImageIcon("/home/tais/Documentos/2022A/Aplicações/HeroFlix/src/main/java/imagens/estrelinha-da-tais.png")); // NOI18N
        btnTres.setBorder(null);
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnQuatro.setBackground(new java.awt.Color(0, 0, 0));
        btnQuatro.setIcon(new javax.swing.ImageIcon("/home/tais/Documentos/2022A/Aplicações/HeroFlix/src/main/java/imagens/estrelinha-da-tais.png")); // NOI18N
        btnQuatro.setBorder(null);
        btnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuatroActionPerformed(evt);
            }
        });

        btnCinco.setBackground(new java.awt.Color(0, 0, 0));
        btnCinco.setIcon(new javax.swing.ImageIcon("/home/tais/Documentos/2022A/Aplicações/HeroFlix/src/main/java/imagens/estrelinha-da-tais.png")); // NOI18N
        btnCinco.setBorder(null);
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnUm.setBackground(new java.awt.Color(0, 0, 0));
        btnUm.setIcon(new javax.swing.ImageIcon("/home/tais/Documentos/2022A/Aplicações/HeroFlix/src/main/java/imagens/estrelinha-da-tais.png")); // NOI18N
        btnUm.setBorder(null);
        btnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmActionPerformed(evt);
            }
        });

        btnReturn.setBackground(new java.awt.Color(0, 0, 0));
        btnReturn.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(204, 204, 204));
        btnReturn.setText("Voltar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel3)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuatro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDois)
                                    .addComponent(btnUm)
                                    .addComponent(btnTres))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCinco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btnReturn)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmActionPerformed
        JOptionPane.showMessageDialog(null, "Código do filme: " + codFilmeAvaliado);
        
        boolean sucesso = false;
        FilmeControle fControle = new FilmeControle();
         try {
             sucesso = fControle.avaliarFilme(this.codFilmeAvaliado, 1);
             if(sucesso){
                JOptionPane.showMessageDialog(null, "O filme foi avaliado com sucesso");
             }else{
                JOptionPane.showMessageDialog(null, "O filme não foi avaliado, selecione um cliente para apagar");
            }
         } catch (ExceptionDAO ex) {
             Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnUmActionPerformed

    private void btnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoisActionPerformed
        boolean sucesso = false;
        FilmeControle fControle = new FilmeControle();
         try {
             sucesso = fControle.avaliarFilme(this.codFilmeAvaliado, 2);
             if(sucesso){
                JOptionPane.showMessageDialog(null, "O filme foi avaliado com sucesso");
             }else{
                JOptionPane.showMessageDialog(null, "O filme não foi avaliado, selecione um cliente para apagar");
            }
         } catch (ExceptionDAO ex) {
             Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnDoisActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        boolean sucesso = false;
        FilmeControle fControle = new FilmeControle();
         try {
             sucesso = fControle.avaliarFilme(this.codFilmeAvaliado, 3);
             if(sucesso){
                JOptionPane.showMessageDialog(null, "O filme foi avaliado com sucesso");
             }else{
                JOptionPane.showMessageDialog(null, "O filme não foi avaliado, selecione um cliente para apagar");
            }
         } catch (ExceptionDAO ex) {
             Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuatroActionPerformed
        boolean sucesso = false;
        FilmeControle fControle = new FilmeControle();
         try {
             sucesso = fControle.avaliarFilme(this.codFilmeAvaliado, 4);
             if(sucesso){
                JOptionPane.showMessageDialog(null, "O filme foi avaliado com sucesso");
             }else{
                JOptionPane.showMessageDialog(null, "O filme não foi avaliado, selecione um cliente para apagar");
            }
         } catch (ExceptionDAO ex) {
             Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnQuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        boolean sucesso = false;
        FilmeControle fControle = new FilmeControle();
         try {
             sucesso = fControle.avaliarFilme(this.codFilmeAvaliado, 5);
             if(sucesso){
                JOptionPane.showMessageDialog(null, "O filme foi avaliado com sucesso");
             }else{
                JOptionPane.showMessageDialog(null, "O filme não foi avaliado, selecione um cliente para apagar");
            }
         } catch (ExceptionDAO ex) {
             Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        TelaConsultaFilmeUser telaConsulta = new TelaConsultaFilmeUser();
        this.setVisible(false);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAvaliacaoFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAvaliacaoFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnDois;
    private javax.swing.JButton btnQuatro;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
